server:
  port: 8079
  servlet:
    context-path: /uaa
  ssl:
    key-store: "${user.dir}/../certs/private.p12"
    key-store-password: "changeit"
    key-alias: "localhost"
    trust-store: "${user.dir}/../certs/trust.jks"
    trust-store-password: "changeit"
    enabled: false
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
  forward-headers-strategy: framework

spring:
  application:
    name: jdbc-oauth2-server
  main:
    banner-mode: off
  datasource:
    url: "jdbc:postgresql://localhost:5432/prore?currentSchema=oauth2"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      pool-name: "auth-server-ds"
      maximum-pool-size: 7
      minimum-idle: 1
    username: "postgres"
    password: ""
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  session:
    redis:
      namespace: sas:session
      flush-mode: on_save
      save-mode: on_set_attribute
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info
    "org.springframework.security.web": debug
    "org.springframework.security.oauth2": debug
    "com.github.brane08.oauth2.server": debug
