server:
  port: 8077
  ssl:
    key-store-type: PKCS12
    key-store: "${user.dir}/../certs/sas.p12"
    key-store-password: "changeit"
    key-alias: "sas"
    enabled: false
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        secure: false
        same-site: lax

spring:
  application:
    name: static-oauth2-server
  main:
    banner-mode: off
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
  session:
    redis:
      namespace: sas:session
      flush-mode: on_save
      save-mode: on_set_attribute
  data:
    redis:
      host: localhost
      port: 6379
  web:
    error:
      include-exception: true
      include-stacktrace: always
      include-message: always

logging:
  level:
    root: info
    "org.springframework.security.web": debug
    "org.springframework.security.oauth2": debug
    "com.github.brane08.oauth2.server": debug
    "org.springframework.data.redis": debug
    "org.springframework.session.redis": debug
